services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    env_file:
      - .env
 
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"